### ISSUE TITLE
Resource not found exception

### ISSUE THREAD

**Issue by Raiz08** [helpcrunch/android-sdk-demo#86]
Fatal Exception: android.content.res.Resources$NotFoundException
Font resource ID #0x7f09000a could not be retrieved.
androidx.core.content.res.ResourcesCompat.loadFont (ResourcesCompat.java:570)

androidx.core.content.res.ResourcesCompat.getFont (ResourcesCompat.java:411)
com.helpcrunch.library.utils.views.toolbar.HCAgentsView.a (SourceFile:410)
com.helpcrunch.library.utils.views.toolbar.HCAgentsView.a (SourceFile:351)
com.helpcrunch.library.utils.views.toolbar.HCAgentsView.a (SourceFile:344)
com.helpcrunch.library.utils.views.toolbar.HCAgentsView.a (SourceFile:337)
com.helpcrunch.library.utils.views.toolbar.HCAgentsView.b (SourceFile:15)
com.helpcrunch.library.utils.views.toolbar.HCAgentsView.a (SourceFile:19)
com.helpcrunch.library.utils.views.toolbar.HCToolbarView.a (SourceFile:439)
com.helpcrunch.library.ui.screens.chat.HcChatFragment.a (SourceFile:3341)
com.helpcrunch.library.ui.screens.chat.HcChatFragment.a (SourceFile:5)

**Comment by TalbotGooday** [comment]
Fixed in 3.3.8

**Comment by Raiz08** [comment]
@TalbotGooday  We are using "3.3.8" version but still getting same issue

**Comment by TalbotGooday** [comment]
@Raiz08 Thanks for the reporting. Yes, we found that this is happening on the notifications. Will be fixed in 3.3.9
